documents:
  - template: contract.md
    output: contract_example.md
    context:
      contract_number: "12345/2025"
      city: "Москва"
      date: "17.03.2025"
      company_name: "ООО Рога и Копыта"
      representative: "Иванова Ивана Ивановича"
      basis: "Устава"
      contractor_name: "Петров Петр Петрович"
      subject: "Исполнитель обязуется оказать услуги по разработке программного обеспечения согласно Техническому заданию"
      contractor_obligations:
        - "Выполнить работы качественно и в срок"
        - "Предоставить отчет о проделанной работе"
        - "Внести исправления по замечаниям Заказчика"
      client_obligations:
        - "Предоставить необходимые материалы и информацию"
        - "Принять и оплатить работу в установленный срок"
      cost: "100000"
      payment_terms: "50% предоплата, 50% после выполнения работ"
      start_date: "17.03.2025"
      end_date: "17.04.2025"
      client_signature: "Иванов И.И."
      contractor_signature: "Петров П.П."
